include:
  - project: "sanger-pathogens/templates/ci-templates"
    ref: "$CI_CD_TEMPLATES_LATEST_STABLE"
    file: "Pipelines/PaM-Info-Nextflow.gitlab-ci.yml"

pytest:
  extends: .before_build_job_template
  before_script:
    - pip install --upgrade pip
    - pip install pytest
  script:
    - pytest -vv
